### ISSUE TITLE
proportion the cc by image to size of original image

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/ProxyFileHandler#1]
proportion the cc by image to size of original image

**Comment by gavinharriss** [comment]
Slightly different approach agreed: We extend the bottom of the image and add copyright image and info at bottom (info will be configured, so can change photo by photo), so not covering any photography detail.

**Comment by gavinharriss** [comment]
At present I'm add 5% to the height of the photo and adding copyright image below. Example attached.
![yyy 8](https://cloud.githubusercontent.com/assets/1517976/11617454/549ea81e-9cf4-11e5-8499-779e58a0bd95.jpg)

**Comment by gavinharriss** [comment]
With a little bit more playing I think we could do something like this:
![copyright-mockup](https://cloud.githubusercontent.com/assets/1517976/11617494/04603aec-9cf5-11e5-9e44-958dc370edc3.jpg)

What do you think? Way we should do it?

**Comment by ndrgriffiths** [comment]
That bottom one looks the tidiest to me but I think either/or would be fine. So would that enable us to add a copyright message specific to a certain set of images? 

This looks like a good way to go rather than having the watermark, as all of the photos are named, labelled etc. so differently that its impossible to put it somewhere that works well for all.

**Comment by gavinharriss** [comment]
I've already coded up the first simpler option. But with a little bit of effort I should be able to get the 2nd option up and running.

The text would be configurable based on image, initially I think we should limit this to the copyright owner's name for the image.

**Comment by coomsie** [comment]
second is fine with me.

**Comment by gavinharriss** [comment]
I've now deployed to test for checking.

If no copyright text is present then it'll default to "Environment Canterbury" e.g.
http://test.canterburymaps.govt.nz/WebApps/FileHandler/proxy.ashx?url=nothing&filename=\Historic_Flood_Imagery\19920830\Original\305%20-%20Christchurch%20from%20near%20Briggs%20Road%20(south)%20-%2030-8-92.jpg

And an example with provided copyright text:
http://test.canterburymaps.govt.nz/WebApps/FileHandler/proxy.ashx?url=nothing&filename=\Historic_Flood_Imagery\19920830\Original\305%20-%20Christchurch%20from%20near%20Briggs%20Road%20(south)%20-%2030-8-92.jpg&copyright=Some%20Copyright%20Holders%20Name%20Here

I still need to hook up the extra "copyright" parameter in FIR and HIR before we can use.

Also, I believe Iain mentioned that this file handler is used by other projects. Can they use as-is with the new copyright tweaks?

BTW: A lot of photos are served up as "application/octet-stream" so don't get caught by the file handlers image mime check, so these photos just get passed straight through without copyright / watermark being added as the current logic stands.

**Comment by coomsie** [comment]
other ap uses these urls ..

original to download
http://canterburymaps.govt.nz/WebApps/FileHandler/proxy.ashx?url=nothing&filename=/Historic_Aerial_Imagery/SN12208/Original/SN12208%20Run%20R%20Photo%2032%2023%20Jun%201995.jpg

thumbnails

http://canterburymaps.govt.nz/WebApps/FileHandler/proxy.ashx?url=nothing&filename=/Historic_Aerial_Imagery/SN12208/Thumbnail/SN12208%20Run%20R%20Photo%2032%2023%20Jun%201995.jpg

**Comment by gavinharriss** [comment]
Bug fixed, and seems to work quickly when even generating lots of thumbnail images with copyright present.

Still only deployed to test.

Urls for images come from ArcGIS service so best place to add the extra "copyright" url param will be there.

**Comment by coomsie** [comment]
Can you hook the test system both FIR AND HIR up tot he test proxy handler so we Nick and I can sign off ... then we can get this in before the code freeze

**Comment by coomsie** [comment]
http://test.canterburymaps.govt.nz/WebApps/FileHandler/proxy.ashx?url=nothing&filename=/Historic_Aerial_Imagery/SN12208/Thumbnail/SN12208%20Run%20R%20Photo%2032%2023%20Jun%201995.jpg

http://test.canterburymaps.govt.nz/WebApps/FileHandler/proxy.ashx?url=nothing&filename=/Historic_Aerial_Imagery/SN12208/Original/SN12208%20Run%20R%20Photo%2032%2023%20Jun%201995.jpg

**Comment by gavinharriss** [comment]
The image urls are coming directly from the ArcGIS service I believe. To test I had to hack some code to swap ArcGIS provided urls with test versions. I could always deploy this hack if you'd like to test on test versions of FIR and HIR?

**Comment by coomsie** [comment]
Right. We can get Hamish to stand up a test Gis service. Maybe show me timers on yr device.

It looks good to go in my mind. So maybe a quick test by me and we can release it.

Cheers
Iain

Sent from my iPhone 5

On 9/12/2015, at 5:57 PM, gavinharriss <notifications@github.com<mailto:notifications@github.com>> wrote:


The image urls are coming directly from the ArcGIS service I believe. To test I had to hack some code to swap ArcGIS provided urls with test versions. I could always deploy this hack if you'd like to test on test versions of FIR and HIR?

-

**Comment by coomsie** [comment]
looks good
