### ISSUE TITLE
Preserve photo EXIF metadata

### ISSUE THREAD

**Issue by gavinharriss** [CanterburyRegionalCouncil/ProxyFileHandler#5]
Email from Nick Griffiths:

If Hamish didn’t mention already, he reckoned the issue with the exif data being stripped from the downloaded images could be being caused by the addition of the watermark, and that you might need to look into this one.

**Comment by gavinharriss** [comment]
Fixed this issue in commit 3e20bfa2d9da083b1d6f12db7f5e7f3a21637d66
Also fixed handler to be async and so allow async calls to Google Analytics etc.

Deployed to test for checking.

**Comment by ndrgriffiths** [comment]
Have just been testing this. Initially didn't seem to be working at all but now seems to be good for some photos but not others. Is it possible that its taking a while to take effect? I noticed a problem with the times while looking at this too which I'll add in as a separate issue.

**Comment by gavinharriss** [comment]
It actually took me a while to find photo with exif metadata to test with, so I suspect the raw images you're testing don't always have anything exif properties to preserve.

Hamish confirms that many photos are missing this meta data. The ones you've added it to are probably the ones you want to use as test photos.

**Comment by ndrgriffiths** [comment]
Yeah its mostly just the newer photos that have anything useful at the moment as most of the old ones are scans. I intend to eventually geotag the ground photos and add in date taken etc. to them all so just wanted to make sure this will stick with the downloaded versions. Seems to still be working fine for some (e.g. 0046 - 10-06-2014) but not others (e.g. 0538 & 0712 - 23-06-2013)

**Comment by ndrgriffiths** [comment]
Have checked this again today on both the live and test versions and all of the ones I checked (including the examples above which hadn't worked previously) seem to be working fine now.
