### ISSUE TITLE
Some photo times out by 1 hour

### ISSUE THREAD

**Issue by ndrgriffiths** [CanterburyRegionalCouncil/ProxyFileHandler#8]
The times that display for each photo appear to be 1 hour earlier than the actual time that I've recorded in the date-time field (e.g. displays as 9:41 a.m. when it should be 10:41 a.m.). This doesn't seem to be an issue with the photos that were taken during summer which makes me suspect it's somehow related to daylight savings?

**Comment by gavinharriss** [comment]
I don't think we add any times to the photo via the file handler. Suspect this issue should be for https://github.com/CanterburyRegionalCouncil/ImageryExplorer project.

Added you to ProxyFileHandler repro and should have perhaps mentioned this part of the solution is only for serving up the raw imagery and adding copyright label to photo.

**Comment by ndrgriffiths** [comment]
Sweet. Took me a while to realise this was a different thing, will add it into the other one
